name: Weekly Notebook Test (YC FC)

on:
  schedule:
    - cron: '0 0 * * 4'       # Запуск каждое четверг в 00:00 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Create .env file
        run: |
          echo "FOLDER_ID=${{ secrets.FOLDER_ID }}" >> .env
          echo "YANDEX_API_KEY=${{ secrets.YANDEX_API_KEY }}" >> .env
          echo "PROXY_URL=${{ secrets.PROXY_URL }}" >> .env

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r yc/function_calling_api/requirements.txt
          pip install jupyter nbconvert
          
      - name: Execute notebook
        run: |
          jupyter nbconvert --to notebook --execute yc/function_calling_api/lesson.ipynb --output executed_notebook.ipynb